### ISSUE TITLE
Child routes don't render in tabs

### ISSUE THREAD

**Issue by fsproru** [bhuh12/vue-router-tab#78] opened 2020-09-24 00:05 UTC
**Describe the bug**
When defining additional child routes as `children`, the child routes don't render in tab view.

**To Reproduce**

1. Clone https://github.com/bhuh12/router-tab-sample
2. Make the page route a child route of /about by changing the following files:
src/router/index.js

``` js
const routes = [
  {
    path: '/',
    component: Frame,
    children: [
      // 引入 RouterTab 内置路由以支持 iframe 页签
      ...RouterTabRoutes,
      {
        path: '/', // 默认页和父级路由一致
        name: 'Home',
        component: importPage('Home'),
        meta: {
          title: 'Home' // 页签标题
        }
      },
      {
        path: '/about',
        name: 'About',
        component: importPage('About'),
        meta: {
          title: 'About' // 页签标题
        },
        children: [
          {
            path: '/page/:id',
            name: 'Page',
            component: importPage('Page'),
            meta: {
              key: 'path',
              title(route) {
                return `Page ${route.params.id}`
              }
            }
          }
        ],
      },
    ]
  }
]
```

App.vue

``` js
      <router-link to="/">Home</router-link>
      <router-link to="/about">About</router-link>
      <router-link to="/about/page/1">Page 1</router-link>
      <router-link to="/about/page/2">Page 2</router-link>
```

3. Run `yarn install` and `yarn serve`
4. Click on Page 1 or Page 2 in the side navigation

**Expected behavior**
Page 1 renders in the tab view, so as page 2. It would be great to have a parameter to control if the child route content is rendered in the same tab or in separate tab per each child route.

**Development Environment (please complete the following information):**

- Node.js: v10.15.2
- Vue: ^2.6.11
- Vue Router ^3.1.5
- **Vue Router Tab** latest

**Operating Environment (please complete the following information):**

- Device: Desktop
- OS: macOS Catalina
- Browser: Chrome
- Version: Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by bhuh12** [comment] 2020-09-24 03:34
Duplicate of #32

RouterTab is deliberately designed in this way. Only the direct sub-routes of routes that use the RouterTab component will generate the tab page. The nested lower-level routing is displayed as in Vue Router.

Imagine that there are **subtabs** inside our tab page, and the subtabs also need to respond to routing. This scenario must be supported by nested routing

It would be very messy for all tab routing to be placed directly on the same layer. We can use the `...` expansion operator to merge and import the routing configuration of different modules:

```javascript
// RouterTab built-in routing
import {RouterTabRoutes} from'vue-router-tab'

const news = [{...}]
const product = [{...}]

const routes = [
   {
     path:'/',
     component: Frame,
     children: [
       ...RouterTabRoutes,
       ...news,
       ...product,
     ]
   }
]
```

_Originally posted by @bhuh12 in https://github.com/bhuh12/vue-router-tab/issues/32#issuecomment-558507640_

**Comment by fsproru** [comment] 2020-09-24 03:43
Got it, we'll use the flattened routes then. It'll be even simpler.

**Closed** 2020-09-24 03:42 UTC
Labels: bug, good first issue
